#!/bin/bash
# HPE Smart Array RAID Monitoring Installer
#
# Installs ssacli + Zabbix Agent2 UserParameters + health check script
# for HPE Smart Array controllers (P408i-a, P816i-a, and other PQI-based controllers)
#
# Tested on:
#   - Proxmox VE 8.x (Debian 12 bookworm)
#   - Proxmox VE 9.x (Debian 13 trixie)
#   - Zabbix Agent2 7.x
#
# Usage:
#   chmod +x install_hpe_raid_monitor.sh
#   sudo ./install_hpe_raid_monitor.sh
#
# After installation, link the Zabbix template to the host:
#   Configuration -> Hosts -> [this host] -> Templates -> HPE Smart Array RAID
#
# https://github.com/oh2lak/HPE-RAID-Zabbix

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail() { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

echo "================================================"
echo " HPE Smart Array RAID Monitor - Installer"
echo "================================================"
echo ""

# --- Preflight checks ---

if [ "$EUID" -ne 0 ]; then
    fail "Please run as root: sudo $0"
fi

# Check for HPE controller
if ! lspci 2>/dev/null | grep -qi "smart array\|hpe.*raid\|hewlett.*raid\|smart storage pqi\|adaptec smart"; then
    warn "No HPE Smart Array controller detected via lspci."
    read -rp "Continue anyway? (y/n): " CONT
    [[ "$CONT" =~ ^[Yy]$ ]] || exit 0
fi

# Check for Zabbix Agent2
if ! systemctl list-units --type=service 2>/dev/null | grep -q "zabbix-agent2"; then
    warn "zabbix-agent2 service not found."
    warn "UserParameter will be installed anyway - start the agent manually later."
    ZABBIX_PRESENT=0
else
    ZABBIX_PRESENT=1
fi

# --- HPE repository and ssacli ---

echo ""
echo ">>> Installing ssacli..."

# HPE repository supports up to bookworm - use it for trixie as well
HPE_DIST="bookworm"
log "Using HPE repository: ${HPE_DIST}"

# Download and install GPG keys
curl -fsSL \
    https://downloads.linux.hpe.com/SDR/hpePublicKey2048_key1.pub \
    https://downloads.linux.hpe.com/SDR/hpePublicKey2048_key2.pub | \
    gpg --dearmor > /usr/share/keyrings/hpe-mcp.gpg 2>/dev/null || \
    fail "Failed to download HPE GPG keys"

log "HPE GPG keys installed"

# Add repository
echo "deb [signed-by=/usr/share/keyrings/hpe-mcp.gpg] https://downloads.linux.hpe.com/SDR/repo/mcp ${HPE_DIST}/current non-free" \
    > /etc/apt/sources.list.d/hpe-mcp.list

# Install ssacli
apt-get update -qq 2>/dev/null
apt-get install -y ssacli 2>/dev/null || fail "Failed to install ssacli"

log "ssacli installed: $(ssacli version 2>/dev/null | head -1 || echo 'OK')"

# --- Detect controller slot ---

echo ""
echo ">>> Detecting HPE controller..."

SLOT=$(ssacli ctrl all show 2>/dev/null | grep -oP 'Slot \K[0-9]+' | head -1)

if [ -z "$SLOT" ]; then
    warn "No controller found via ssacli. Defaulting to slot=0."
    SLOT=0
else
    log "Controller found in slot: ${SLOT}"
fi

# --- Install health check script ---

echo ""
echo ">>> Installing health check script..."

cat > /usr/local/bin/hpe_raid_check.sh << EOF
#!/bin/bash
# HPE Smart Array RAID health check
# Generated by install_hpe_raid_monitor.sh

SLOT=${SLOT}
STATUS="OK"
ISSUES=""

# Check logical drives
LD=\$(ssacli ctrl slot=\$SLOT ld all show status 2>/dev/null)
if echo "\$LD" | grep -qiE "failed|degraded"; then
    STATUS="CRITICAL"
    ISSUES+="\$(echo "\$LD" | grep -iE 'failed|degraded' | xargs) "
fi

# Check physical drives
PD=\$(ssacli ctrl slot=\$SLOT pd all show status 2>/dev/null)
if echo "\$PD" | grep -qiE "failed|predictive failure"; then
    STATUS="CRITICAL"
    ISSUES+="\$(echo "\$PD" | grep -iE 'failed|predictive' | xargs) "
fi

# Check cache / battery
CACHE=\$(ssacli ctrl slot=\$SLOT show detail 2>/dev/null)
if echo "\$CACHE" | grep -qiE "battery/capacitor status: failed"; then
    STATUS="WARNING"
    ISSUES+="Battery/Cache failed "
fi

echo "\${STATUS}\${ISSUES:+: \$ISSUES}"
EOF

chmod +x /usr/local/bin/hpe_raid_check.sh
log "Health check script: /usr/local/bin/hpe_raid_check.sh"

# --- Sudoers ---

cat > /etc/sudoers.d/zabbix-ssacli << EOF
zabbix ALL=(root) NOPASSWD: /usr/bin/ssacli
zabbix ALL=(root) NOPASSWD: /usr/local/bin/hpe_raid_check.sh
EOF
chmod 440 /etc/sudoers.d/zabbix-ssacli
log "Sudoers rule: /etc/sudoers.d/zabbix-ssacli"

# --- Zabbix UserParameters ---

# Find conf.d directory
ZABBIX_CONFD=""
for DIR in \
    /etc/zabbix/zabbix_agent2.d \
    /etc/zabbix/zabbix_agentd.d \
    /usr/local/etc/zabbix_agent2.d; do
    if [ -d "$DIR" ]; then
        ZABBIX_CONFD="$DIR"
        break
    fi
done

if [ -z "$ZABBIX_CONFD" ]; then
    warn "Zabbix conf.d directory not found. Creating /etc/zabbix/zabbix_agent2.d"
    mkdir -p /etc/zabbix/zabbix_agent2.d
    ZABBIX_CONFD="/etc/zabbix/zabbix_agent2.d"
fi

cat > "${ZABBIX_CONFD}/hpe_raid.conf" << EOF
UserParameter=hpe.raid.status,sudo /usr/local/bin/hpe_raid_check.sh
UserParameter=hpe.raid.ld.raw,sudo ssacli ctrl slot=${SLOT} ld all show status 2>/dev/null
UserParameter=hpe.raid.pd.raw,sudo ssacli ctrl slot=${SLOT} pd all show status 2>/dev/null
UserParameter=hpe.raid.ctrl.temp,sudo ssacli ctrl slot=${SLOT} show detail 2>/dev/null | grep -A2 "Location: ASIC" | grep "Current Value" | awk '{print \$4}'
EOF

log "UserParameters: ${ZABBIX_CONFD}/hpe_raid.conf"

# --- Restart Zabbix agent ---

if [ "$ZABBIX_PRESENT" -eq 1 ]; then
    systemctl restart zabbix-agent2 2>/dev/null || \
    systemctl restart zabbix-agent 2>/dev/null || \
    warn "Could not restart Zabbix agent - please restart it manually"
    log "Zabbix agent restarted"
fi

# --- Self-test ---

echo ""
echo ">>> Running self-test..."
sleep 1

RESULT=$(/usr/local/bin/hpe_raid_check.sh 2>/dev/null)
if [[ "$RESULT" == OK* ]]; then
    log "Self-test passed: ${RESULT}"
else
    warn "Self-test returned: ${RESULT}"
fi

echo ""
echo "================================================"
echo " Installation complete!"
echo "================================================"
echo ""
echo " Health check:  /usr/local/bin/hpe_raid_check.sh"
echo " UserParameter: ${ZABBIX_CONFD}/hpe_raid.conf"
echo " RAID slot:     ${SLOT}"
echo ""
echo " Next step: link the Zabbix template to this host:"
echo " Configuration -> Hosts -> $(hostname) -> Templates"
echo " -> HPE Smart Array RAID"
echo ""
