#!/bin/bash
# install_hpe_raid_monitor.sh
# Installs HPE Smart Array RAID monitoring for Zabbix Agent2.
# https://github.com/OH2LAK/hpe-raid-zabbix
#
# Tested on:
#   - HPE Smart Array P408i-a SR Gen10
#   - Proxmox VE 8.x (Debian 12 bookworm) and 9.x (Debian 13 trixie)
#   - Zabbix Agent2 7.0 LTS
#
# Should work on any HPE server with a PQI/Adaptec-based Smart Array
# controller on a Debian-based OS.

set -e

log()  { echo "[OK]   $1"; }
warn() { echo "[WARN] $1"; }
err()  { echo "[FAIL] $1"; exit 1; }

echo "================================================"
echo " HPE Smart Array RAID monitoring - installer"
echo "================================================"
echo ""

# --- Must be root ---
if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root."
fi

# --- Detect ssacli ---
echo ">>> Locating ssacli..."
SSACLI_PATH="$(command -v ssacli || true)"

if [ -z "$SSACLI_PATH" ]; then
    err "ssacli not found. Install the HPE Smart Storage Administrator CLI (ssacli) first: https://support.hpe.com"
fi
log "Found ssacli at: ${SSACLI_PATH}"

# --- Detect controller presence (sanity check) ---
if ! lspci | grep -qiE "smart storage pqi|adaptec smart|smart array"; then
    warn "No HPE/Adaptec Smart Array controller detected via lspci. Continuing anyway, but double-check this is the right host."
fi

# --- Detect controller slot ---
echo ""
echo ">>> Detecting controller slot..."
SLOT="$("$SSACLI_PATH" ctrl all show config 2>/dev/null | grep -oP 'Slot \K[0-9]+' | head -1)"
if [ -z "$SLOT" ]; then
    warn "Could not auto-detect controller slot. Defaulting to slot=0."
    SLOT=0
else
    log "Controller found in slot: ${SLOT}"
fi

# --- Detect Zabbix agent presence ---
ZABBIX_PRESENT=0
if systemctl list-unit-files 2>/dev/null | grep -q zabbix-agent2; then
    ZABBIX_PRESENT=1
    log "zabbix-agent2 detected"
else
    warn "zabbix-agent2 not detected - the UserParameter file will still be installed, but you'll need to install and configure Zabbix Agent2 separately."
fi

# --- Install health check script ---
echo ""
echo ">>> Installing health check script..."

cat > /usr/local/bin/hpe_raid_check.sh << EOF
#!/bin/bash
# HPE Smart Array RAID health check
# Generated by install_hpe_raid_monitor.sh
# ssacli path is hardcoded to match the sudoers rule created by this installer.

SSACLI="${SSACLI_PATH}"
SLOT=${SLOT}
STATUS="OK"
ISSUES=""

LD=\$(\$SSACLI ctrl slot=\$SLOT ld all show status 2>/dev/null)
if echo "\$LD" | grep -qiE "failed|degraded"; then
    STATUS="CRITICAL"
    ISSUES+="\$(echo "\$LD" | grep -iE 'failed|degraded' | xargs) "
fi

PD=\$(\$SSACLI ctrl slot=\$SLOT pd all show status 2>/dev/null)
if echo "\$PD" | grep -qiE "failed|predictive failure"; then
    STATUS="CRITICAL"
    ISSUES+="\$(echo "\$PD" | grep -iE 'failed|predictive' | xargs) "
fi

CACHE=\$(\$SSACLI ctrl slot=\$SLOT show detail 2>/dev/null)
if echo "\$CACHE" | grep -qiE "battery/capacitor status: failed"; then
    STATUS="WARNING"
    ISSUES+="Battery/Cache failed "
fi

echo "\${STATUS}\${ISSUES:+: \$ISSUES}"
EOF

chmod +x /usr/local/bin/hpe_raid_check.sh
log "Health check script: /usr/local/bin/hpe_raid_check.sh"

# --- Sudoers ---
echo ""
echo ">>> Configuring sudoers..."

cat > /etc/sudoers.d/zabbix-ssacli << EOF
zabbix ALL=(root) NOPASSWD: ${SSACLI_PATH}
zabbix ALL=(root) NOPASSWD: /usr/local/bin/hpe_raid_check.sh
EOF
chmod 440 /etc/sudoers.d/zabbix-ssacli

# Validate the sudoers file before relying on it
if ! visudo -cf /etc/sudoers.d/zabbix-ssacli > /dev/null 2>&1; then
    err "Generated sudoers file failed validation - check /etc/sudoers.d/zabbix-ssacli manually."
fi
log "Sudoers rule: /etc/sudoers.d/zabbix-ssacli (path matches ssacli at ${SSACLI_PATH})"

# --- Zabbix UserParameters ---
echo ""
echo ">>> Installing Zabbix UserParameters..."

ZABBIX_CONFD=""
for DIR in \
    /etc/zabbix/zabbix_agent2.d \
    /etc/zabbix/zabbix_agentd.d \
    /usr/local/etc/zabbix_agent2.d; do
    if [ -d "$DIR" ]; then
        ZABBIX_CONFD="$DIR"
        break
    fi
done

if [ -z "$ZABBIX_CONFD" ]; then
    warn "Zabbix conf.d directory not found. Creating /etc/zabbix/zabbix_agent2.d"
    mkdir -p /etc/zabbix/zabbix_agent2.d
    ZABBIX_CONFD="/etc/zabbix/zabbix_agent2.d"
fi

cat > "${ZABBIX_CONFD}/hpe_raid.conf" << EOF
UserParameter=hpe.raid.status,sudo /usr/local/bin/hpe_raid_check.sh
UserParameter=hpe.raid.ld.raw,sudo ${SSACLI_PATH} ctrl slot=${SLOT} ld all show status 2>/dev/null
UserParameter=hpe.raid.pd.raw,sudo ${SSACLI_PATH} ctrl slot=${SLOT} pd all show status 2>/dev/null
UserParameter=hpe.raid.ctrl.temp,sudo ${SSACLI_PATH} ctrl slot=${SLOT} show detail 2>/dev/null | grep -A2 "Location: ASIC" | grep "Current Value" | awk '{print \$4}'
EOF

log "UserParameters: ${ZABBIX_CONFD}/hpe_raid.conf"

# --- Restart Zabbix agent ---
if [ "$ZABBIX_PRESENT" -eq 1 ]; then
    systemctl restart zabbix-agent2 2>/dev/null || \
    systemctl restart zabbix-agent 2>/dev/null || \
    warn "Could not restart Zabbix agent - please restart it manually."
    log "Zabbix agent restarted"
fi

# --- Self-test ---
echo ""
echo ">>> Running self-test..."
sleep 1

RESULT=$(su -s /bin/bash zabbix -c "sudo /usr/local/bin/hpe_raid_check.sh" 2>&1 || true)
if [[ "$RESULT" == OK* ]]; then
    log "Self-test passed (run as zabbix user via sudo): ${RESULT}"
else
    warn "Self-test returned: ${RESULT}"
    warn "If this mentions a password prompt or 'not allowed', double-check that ${SSACLI_PATH} matches the path in /etc/sudoers.d/zabbix-ssacli exactly."
fi

echo ""
echo "================================================"
echo " Installation complete!"
echo "================================================"
echo ""
echo " Health check:   /usr/local/bin/hpe_raid_check.sh"
echo " UserParameter:  ${ZABBIX_CONFD}/hpe_raid.conf"
echo " ssacli path:    ${SSACLI_PATH}"
echo " RAID slot:      ${SLOT}"
echo ""
echo " Next step: link the Zabbix template to this host:"
echo " Data collection -> Hosts -> $(hostname) -> Templates"
echo " -> HPE Smart Array RAID"
echo ""
